-- Deletes the unreliable "aigner-full-*" batch (data generated by ChatGPT
-- that didn't actually match the images) and replaces it with 81 products
-- whose price/color/gender were read directly from the original watermarked
-- photos by Claude. Run AFTER uploading Downloads/aigner-verified/*.png to
-- the "products" bucket root.

delete from products where slug like 'aigner-full-%';

do $$
declare
  v_brand_id uuid;
  v_category_id uuid;
  v_base text := 'https://hgqtaynglxeovzyzlkqe.supabase.co/storage/v1/object/public/products/';
  v_product_id uuid;
begin
  select id into v_brand_id from brands where slug = 'aigner';
  select id into v_category_id from categories where slug = 'watches';

  -- helper pattern repeated for each verified watch
  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - فضي - 01', 'aigner-verified-01', 'ساعة أقنر نسائي بتصميم فضي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'فضي', 'AIGV-01', 139.000, 1, v_base || 'av-01.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - أخضر جلد - 02', 'aigner-verified-02', 'ساعة أقنر نسائي بتصميم أخضر جلد. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'أخضر جلد', 'AIGV-02', 109.000, 1, v_base || 'av-02.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - فضي - 03', 'aigner-verified-03', 'ساعة أقنر نسائي بتصميم فضي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'فضي', 'AIGV-03', 149.000, 1, v_base || 'av-03.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - أبيض جلد - 04', 'aigner-verified-04', 'ساعة أقنر نسائي بتصميم أبيض جلد. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'أبيض جلد', 'AIGV-04', 119.000, 1, v_base || 'av-04.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - فضي وذهبي - 05', 'aigner-verified-05', 'ساعة أقنر نسائي بتصميم فضي وذهبي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'فضي وذهبي', 'AIGV-05', 179.000, 1, v_base || 'av-05.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر رجالي - فضي - 06', 'aigner-verified-06', 'ساعة أقنر رجالي بتصميم فضي. تسليم فوري مع كامل ملحقات الماركة.', 'men')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'فضي', 'AIGV-06', 169.000, 1, v_base || 'av-06.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - ذهبي - 07', 'aigner-verified-07', 'ساعة أقنر نسائي بتصميم ذهبي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'ذهبي', 'AIGV-07', 219.000, 1, v_base || 'av-07.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - فضي - 08', 'aigner-verified-08', 'ساعة أقنر نسائي بتصميم فضي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'فضي', 'AIGV-08', 129.000, 1, v_base || 'av-08.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - فضي - 09', 'aigner-verified-09', 'ساعة أقنر نسائي بتصميم فضي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'فضي', 'AIGV-09', 149.000, 1, v_base || 'av-09.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر رجالي - أسود جلد - 10', 'aigner-verified-10', 'ساعة أقنر رجالي بتصميم أسود جلد. تسليم فوري مع كامل ملحقات الماركة.', 'men')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'أسود جلد', 'AIGV-10', 198.000, 1, v_base || 'av-10.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - ذهبي وجلد أسود - 11', 'aigner-verified-11', 'ساعة أقنر نسائي بتصميم ذهبي وجلد أسود. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'ذهبي وجلد أسود', 'AIGV-11', 119.000, 1, v_base || 'av-11.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - ذهبي - 12', 'aigner-verified-12', 'ساعة أقنر نسائي بتصميم ذهبي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'ذهبي', 'AIGV-12', 179.000, 1, v_base || 'av-12.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - أخضر وذهبي - 13', 'aigner-verified-13', 'ساعة أقنر نسائي بتصميم أخضر وذهبي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'أخضر وذهبي', 'AIGV-13', 179.000, 1, v_base || 'av-13.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - فوشي جلد - 14', 'aigner-verified-14', 'ساعة أقنر نسائي بتصميم فوشي جلد. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'فوشي جلد', 'AIGV-14', 69.000, 1, v_base || 'av-14.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - فضي وذهبي - 15', 'aigner-verified-15', 'ساعة أقنر نسائي بتصميم فضي وذهبي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'فضي وذهبي', 'AIGV-15', 179.000, 1, v_base || 'av-15.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - أسود وفضي - 16', 'aigner-verified-16', 'ساعة أقنر نسائي بتصميم أسود وفضي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'أسود وفضي', 'AIGV-16', 109.000, 1, v_base || 'av-16.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - فضي - 17', 'aigner-verified-17', 'ساعة أقنر نسائي بتصميم فضي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'فضي', 'AIGV-17', 129.000, 1, v_base || 'av-17.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - ذهبي وصدفي - 18', 'aigner-verified-18', 'ساعة أقنر نسائي بتصميم ذهبي وصدفي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'ذهبي وصدفي', 'AIGV-18', 169.000, 1, v_base || 'av-18.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - فضي وذهبي - 19', 'aigner-verified-19', 'ساعة أقنر نسائي بتصميم فضي وذهبي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'فضي وذهبي', 'AIGV-19', 189.000, 1, v_base || 'av-19.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - ذهبي - 20', 'aigner-verified-20', 'ساعة أقنر نسائي بتصميم ذهبي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'ذهبي', 'AIGV-20', 198.000, 1, v_base || 'av-20.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - ذهبي وجلد أبيض - 21', 'aigner-verified-21', 'ساعة أقنر نسائي بتصميم ذهبي وجلد أبيض. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'ذهبي وجلد أبيض', 'AIGV-21', 59.000, 1, v_base || 'av-21.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - فضي وذهبي - 22', 'aigner-verified-22', 'ساعة أقنر نسائي بتصميم فضي وذهبي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'فضي وذهبي', 'AIGV-22', 159.000, 1, v_base || 'av-22.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - ذهبي وجلد أبيض - 23', 'aigner-verified-23', 'ساعة أقنر نسائي بتصميم ذهبي وجلد أبيض. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'ذهبي وجلد أبيض', 'AIGV-23', 109.000, 1, v_base || 'av-23.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - فضي وذهبي - 24', 'aigner-verified-24', 'ساعة أقنر نسائي بتصميم فضي وذهبي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'فضي وذهبي', 'AIGV-24', 169.000, 1, v_base || 'av-24.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - فضي وذهبي - 25', 'aigner-verified-25', 'ساعة أقنر نسائي بتصميم فضي وذهبي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'فضي وذهبي', 'AIGV-25', 109.000, 1, v_base || 'av-25.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - ذهبي - 26', 'aigner-verified-26', 'ساعة أقنر نسائي بتصميم ذهبي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'ذهبي', 'AIGV-26', 159.000, 1, v_base || 'av-26.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - فضي - 27', 'aigner-verified-27', 'ساعة أقنر نسائي بتصميم فضي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'فضي', 'AIGV-27', 149.000, 1, v_base || 'av-27.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - فضي - 28', 'aigner-verified-28', 'ساعة أقنر نسائي بتصميم فضي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'فضي', 'AIGV-28', 165.000, 1, v_base || 'av-28.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر رجالي - ذهبي وفضي - 29', 'aigner-verified-29', 'ساعة أقنر رجالي بتصميم ذهبي وفضي. تسليم فوري مع كامل ملحقات الماركة.', 'men')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'ذهبي وفضي', 'AIGV-29', 159.000, 1, v_base || 'av-29.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - فضي وذهبي - 30', 'aigner-verified-30', 'ساعة أقنر نسائي بتصميم فضي وذهبي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'فضي وذهبي', 'AIGV-30', 179.000, 1, v_base || 'av-30.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - أخضر وذهبي - 31', 'aigner-verified-31', 'ساعة أقنر نسائي بتصميم أخضر وذهبي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'أخضر وذهبي', 'AIGV-31', 169.000, 1, v_base || 'av-31.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - فضي وذهبي - 32', 'aigner-verified-32', 'ساعة أقنر نسائي بتصميم فضي وذهبي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'فضي وذهبي', 'AIGV-32', 179.000, 1, v_base || 'av-32.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - فضي وذهبي وردي - 33', 'aigner-verified-33', 'ساعة أقنر نسائي بتصميم فضي وذهبي وردي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'فضي وذهبي وردي', 'AIGV-33', 119.000, 1, v_base || 'av-33.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - كحلي جلد - 34', 'aigner-verified-34', 'ساعة أقنر نسائي بتصميم كحلي جلد. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'كحلي جلد', 'AIGV-34', 109.000, 1, v_base || 'av-34.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - عنابي وفضي وذهبي - 35', 'aigner-verified-35', 'ساعة أقنر نسائي بتصميم عنابي وفضي وذهبي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'عنابي وفضي وذهبي', 'AIGV-35', 189.000, 1, v_base || 'av-35.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - فضي - 36', 'aigner-verified-36', 'ساعة أقنر نسائي بتصميم فضي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'فضي', 'AIGV-36', 139.000, 1, v_base || 'av-36.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - أخضر وذهبي - 37', 'aigner-verified-37', 'ساعة أقنر نسائي بتصميم أخضر وذهبي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'أخضر وذهبي', 'AIGV-37', 169.000, 1, v_base || 'av-37.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - أخضر وذهبي - 39', 'aigner-verified-39', 'ساعة أقنر نسائي بتصميم أخضر وذهبي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'أخضر وذهبي', 'AIGV-39', 139.000, 1, v_base || 'av-39.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - فضي وذهبي - 40', 'aigner-verified-40', 'ساعة أقنر نسائي بتصميم فضي وذهبي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'فضي وذهبي', 'AIGV-40', 179.000, 1, v_base || 'av-40.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر رجالي - فضي وأزرق - 41', 'aigner-verified-41', 'ساعة أقنر رجالي بتصميم فضي وأزرق. تسليم فوري مع كامل ملحقات الماركة.', 'men')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'فضي وأزرق', 'AIGV-41', 179.000, 1, v_base || 'av-41.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - فضي وذهبي - 42', 'aigner-verified-42', 'ساعة أقنر نسائي بتصميم فضي وذهبي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'فضي وذهبي', 'AIGV-42', 149.000, 1, v_base || 'av-42.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - ذهبي وجلد أبيض - 43', 'aigner-verified-43', 'ساعة أقنر نسائي بتصميم ذهبي وجلد أبيض. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'ذهبي وجلد أبيض', 'AIGV-43', 119.000, 1, v_base || 'av-43.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - عنابي وفضي وذهبي - 44', 'aigner-verified-44', 'ساعة أقنر نسائي بتصميم عنابي وفضي وذهبي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'عنابي وفضي وذهبي', 'AIGV-44', 179.000, 1, v_base || 'av-44.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - ذهبي وجلد أبيض - 45', 'aigner-verified-45', 'ساعة أقنر نسائي بتصميم ذهبي وجلد أبيض. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'ذهبي وجلد أبيض', 'AIGV-45', 119.000, 1, v_base || 'av-45.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - ذهبي وجلد أبيض - 46', 'aigner-verified-46', 'ساعة أقنر نسائي بتصميم ذهبي وجلد أبيض. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'ذهبي وجلد أبيض', 'AIGV-46', 98.000, 1, v_base || 'av-46.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - ذهبي - 47', 'aigner-verified-47', 'ساعة أقنر نسائي بتصميم ذهبي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'ذهبي', 'AIGV-47', 159.000, 1, v_base || 'av-47.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - فضي وذهبي وردي - 48', 'aigner-verified-48', 'ساعة أقنر نسائي بتصميم فضي وذهبي وردي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'فضي وذهبي وردي', 'AIGV-48', 149.000, 1, v_base || 'av-48.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - فضي وذهبي - 49', 'aigner-verified-49', 'ساعة أقنر نسائي بتصميم فضي وذهبي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'فضي وذهبي', 'AIGV-49', 179.000, 1, v_base || 'av-49.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - أخضر وذهبي - 50', 'aigner-verified-50', 'ساعة أقنر نسائي بتصميم أخضر وذهبي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'أخضر وذهبي', 'AIGV-50', 149.000, 1, v_base || 'av-50.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - أزرق وذهبي - 51', 'aigner-verified-51', 'ساعة أقنر نسائي بتصميم أزرق وذهبي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'أزرق وذهبي', 'AIGV-51', 149.000, 1, v_base || 'av-51.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - ذهبي - 52', 'aigner-verified-52', 'ساعة أقنر نسائي بتصميم ذهبي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'ذهبي', 'AIGV-52', 179.000, 1, v_base || 'av-52.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - فوشي جلد - 53', 'aigner-verified-53', 'ساعة أقنر نسائي بتصميم فوشي جلد. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'فوشي جلد', 'AIGV-53', 69.000, 1, v_base || 'av-53.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - فضي وذهبي - 54', 'aigner-verified-54', 'ساعة أقنر نسائي بتصميم فضي وذهبي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'فضي وذهبي', 'AIGV-54', 149.000, 1, v_base || 'av-54.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - أخضر وذهبي - 55', 'aigner-verified-55', 'ساعة أقنر نسائي بتصميم أخضر وذهبي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'أخضر وذهبي', 'AIGV-55', 159.000, 1, v_base || 'av-55.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - فضي وذهبي - 56', 'aigner-verified-56', 'ساعة أقنر نسائي بتصميم فضي وذهبي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'فضي وذهبي', 'AIGV-56', 159.000, 1, v_base || 'av-56.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - أخضر وذهبي - 57', 'aigner-verified-57', 'ساعة أقنر نسائي بتصميم أخضر وذهبي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'أخضر وذهبي', 'AIGV-57', 179.000, 1, v_base || 'av-57.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - أخضر وفضي وذهبي - 58', 'aigner-verified-58', 'ساعة أقنر نسائي بتصميم أخضر وفضي وذهبي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'أخضر وفضي وذهبي', 'AIGV-58', 169.000, 1, v_base || 'av-58.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - فضي - 59', 'aigner-verified-59', 'ساعة أقنر نسائي بتصميم فضي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'فضي', 'AIGV-59', 149.000, 1, v_base || 'av-59.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - فضي وذهبي - 60', 'aigner-verified-60', 'ساعة أقنر نسائي بتصميم فضي وذهبي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'فضي وذهبي', 'AIGV-60', 149.000, 1, v_base || 'av-60.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - بنفسجي جلد - 61', 'aigner-verified-61', 'ساعة أقنر نسائي بتصميم بنفسجي جلد. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'بنفسجي جلد', 'AIGV-61', 99.000, 1, v_base || 'av-61.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - بني فاتح جلد وذهبي - 62', 'aigner-verified-62', 'ساعة أقنر نسائي بتصميم بني فاتح جلد وذهبي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'بني فاتح جلد وذهبي', 'AIGV-62', 99.000, 1, v_base || 'av-62.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - كحلي وفضي وذهبي - 63', 'aigner-verified-63', 'ساعة أقنر نسائي بتصميم كحلي وفضي وذهبي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'كحلي وفضي وذهبي', 'AIGV-63', 149.000, 1, v_base || 'av-63.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - ذهبي وفضي - 64', 'aigner-verified-64', 'ساعة أقنر نسائي بتصميم ذهبي وفضي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'ذهبي وفضي', 'AIGV-64', 179.000, 1, v_base || 'av-64.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - فضي - 65', 'aigner-verified-65', 'ساعة أقنر نسائي بتصميم فضي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'فضي', 'AIGV-65', 149.000, 1, v_base || 'av-65.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - ذهبي - 66', 'aigner-verified-66', 'ساعة أقنر نسائي بتصميم ذهبي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'ذهبي', 'AIGV-66', 198.000, 1, v_base || 'av-66.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - فضي - 67', 'aigner-verified-67', 'ساعة أقنر نسائي بتصميم فضي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'فضي', 'AIGV-67', 159.000, 1, v_base || 'av-67.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - فضي - 68', 'aigner-verified-68', 'ساعة أقنر نسائي بتصميم فضي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'فضي', 'AIGV-68', 119.000, 1, v_base || 'av-68.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - كحلي جلد - 69', 'aigner-verified-69', 'ساعة أقنر نسائي بتصميم كحلي جلد. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'كحلي جلد', 'AIGV-69', 119.000, 1, v_base || 'av-69.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - كحلي جلد - 70', 'aigner-verified-70', 'ساعة أقنر نسائي بتصميم كحلي جلد. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'كحلي جلد', 'AIGV-70', 79.000, 1, v_base || 'av-70.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - وردي وذهبي - 71', 'aigner-verified-71', 'ساعة أقنر نسائي بتصميم وردي وذهبي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'وردي وذهبي', 'AIGV-71', 159.000, 1, v_base || 'av-71.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - أخضر وذهبي - 72', 'aigner-verified-72', 'ساعة أقنر نسائي بتصميم أخضر وذهبي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'أخضر وذهبي', 'AIGV-72', 169.000, 1, v_base || 'av-72.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - فضي وذهبي - 73', 'aigner-verified-73', 'ساعة أقنر نسائي بتصميم فضي وذهبي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'فضي وذهبي', 'AIGV-73', 139.000, 1, v_base || 'av-73.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - أخضر وفضي وذهبي - 74', 'aigner-verified-74', 'ساعة أقنر نسائي بتصميم أخضر وفضي وذهبي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'أخضر وفضي وذهبي', 'AIGV-74', 149.000, 1, v_base || 'av-74.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - أخضر وفضي وذهبي - 75', 'aigner-verified-75', 'ساعة أقنر نسائي بتصميم أخضر وفضي وذهبي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'أخضر وفضي وذهبي', 'AIGV-75', 169.000, 1, v_base || 'av-75.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - أبيض جلد - 76', 'aigner-verified-76', 'ساعة أقنر نسائي بتصميم أبيض جلد. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'أبيض جلد', 'AIGV-76', 89.000, 1, v_base || 'av-76.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - فضي - 77', 'aigner-verified-77', 'ساعة أقنر نسائي بتصميم فضي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'فضي', 'AIGV-77', 129.000, 1, v_base || 'av-77.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - أخضر وفضي وذهبي - 78', 'aigner-verified-78', 'ساعة أقنر نسائي بتصميم أخضر وفضي وذهبي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'أخضر وفضي وذهبي', 'AIGV-78', 179.000, 1, v_base || 'av-78.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - أخضر وفضي وذهبي - 79', 'aigner-verified-79', 'ساعة أقنر نسائي بتصميم أخضر وفضي وذهبي. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'أخضر وفضي وذهبي', 'AIGV-79', 179.000, 1, v_base || 'av-79.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر رجالي - فضي - 80', 'aigner-verified-80', 'ساعة أقنر رجالي بتصميم فضي. تسليم فوري مع كامل ملحقات الماركة.', 'men')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'فضي', 'AIGV-80', 169.000, 1, v_base || 'av-80.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر نسائي - أسود جلد - 81', 'aigner-verified-81', 'ساعة أقنر نسائي بتصميم أسود جلد. تسليم فوري مع كامل ملحقات الماركة.', 'women')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'أسود جلد', 'AIGV-81', 69.000, 1, v_base || 'av-81.png');

  insert into products (brand_id, category_id, name, slug, description, gender)
  values (v_brand_id, v_category_id, 'ساعة أقنر رجالي - بني وفضي وذهبي - 82', 'aigner-verified-82', 'ساعة أقنر رجالي بتصميم بني وفضي وذهبي. تسليم فوري مع كامل ملحقات الماركة.', 'men')
  returning id into v_product_id;
  insert into product_variants (product_id, color, sku, price, stock, image_url)
  values (v_product_id, 'بني وفضي وذهبي', 'AIGV-82', 179.000, 1, v_base || 'av-82.png');

end $$;
